name: Verify

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!release'
  workflow_run:
    workflows: [Release version, Development version]
    types: [completed]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: 'maven'
    - name: Verify with Maven
      run: mvn verify --file pom.xml
